services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    depends_on:
      - jsonserver

  jsonserver:
    image: clue/json-server
    command: ["--watch", "db.json", "--port", "3001"]
    volumes:
      - ./data/db.json:/data/db.json
    expose: 
      - 3001
    networks:
      - react-express


networks:
  react-express: